version: '3.8'

services:

  fastapi:
    build: ./server
    container_name: fastapi
    ports:
      - "5000:5000"
    command:  uvicorn server.backend.main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
    restart: always
    tty: true
    
    
  frontend:
    build: ./app
    command: yarn start
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
    container_name: frontend
    restart: always
    
    

networks:
    default:
        driver: bridge
