version: '3'
services:

  frontend:
    image: node:16-alpine3.12
    command: yarn create nuxt-app
    volumes:
        - ./app:/app
    working_dir: /app
    ports:
        - "3000:3000"
    environment:
        HOST: 0.0.0.0