version: '3.8'

services:

  fastapi:
    build: ./server
    container_name: fastapi
    ports:
      - 8080:8080
    volumes:
      - ./server/backend/main:/app
    environment:
      - DATABASE_URL=sqlite:///./sql_app.db
    command: uvicorn server.backend.main:app --host 0.0.0.0
    restart: always
    tty: true
    

  frontend:
    build: ./app
    command: yarn dev
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - HOST=0.0.0.0
    container_name: frontend
    restart: always
    links:
      - fastapi
    